tasks:
  default:
    task_world: ConversationBotTaskWorld
    timeout: 60
    agents_required: 1
task_name: chatbot
world_module: chatbot.worlds
overworld: ConversationBotTaskWorld
max_workers: 30
opt:  # Additional model opts go here
  models:
    blender_400M:
      model: transformer/generator
      model_file: zoo:blender/blender_400Mdistill/model
      interactive_mode: True
